(part "NCR321PASX"
    (packageRef "NCR321PASX")
    (interface
        (port "1" (symbPinId 1) (portName "VEN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "REXT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "N/C_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "N/C_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IOUT__1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "IOUT__2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "N/C_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "NCR321PASX")
    (property "Description" "LED Driver IC 1 Output Linear Constant Current PWM Dimming 250mA DFN2020D-6")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/NCR320PAS_NCR321PAS.pdf")
    (property "symbolName1" "NCR321PASX")
)
