/* Auto-generated by sim/gen_maze.py -- do not hand-edit. */
#ifndef SIM_MAZE_DATA_H_
#define SIM_MAZE_DATA_H_

#include <stdint.h>

#define SIM_MAZE_SIZE 16
#define SIM_GOAL_X 7
#define SIM_GOAL_Y 7

static const uint32_t TRUE_Maze_Row[17] = {
	65535, 5684, 15042, 38310, 17496, 14526, 21075, 30188, 2596, 7432, 18928, 13000, 30500, 6746, 13356, 6736, 65535
};

static const uint32_t TRUE_Maze_Column[17] = {
	65535, 27539, 42057, 22054, 18764, 48962, 16436, 14728, 27251, 33960, 10056, 18662, 1088, 913, 63278, 31158, 65535
};

#endif /* SIM_MAZE_DATA_H_ */
